export const tokens = ['dict.1.1.20160621T214817Z.d12839c3b95ffec3.e55a508c638acb72bea68e1e86a7ec37592bc874', 'dict.1.1.20160621T214200Z.dec22d89f841297c.f54e574cb34fcabaa29b9202891538ce1cfe08d9'];

export const supportedLanguagesUrl = `https://dictionary.yandex.net/api/v1/dicservice.json/getLangs?key=${tokens[0]}`;

export const translateUrl = 'https://dictionary.yandex.net/api/v1/dicservice.json/lookup?key=';

export const yandexHeaderService = 'Yandex dictionary service';
export const connectionError = 'Connection error';
export const checkInternetConnection = 'Check Internet connection.';
export const actooWillUseSavedData = 'Actoo will use save data';
export const unknownWord = 'Unknown or too long word';
export const typeAnyWord = 'Type any word';
export const emptyDictionaryMessage = 'No dictionary words.\nAdd them via translating.';
export const emptyRemindMessage = 'No words for remind.\nAdd them via translating.';
export const yandexApiText = 'Powered by Yandex.Dictionary';

export const defaultLanguageDirections = [
  'be-ru',
  'bg-ru',
  'cs-en',
  'cs-ru',
  'da-en',
  'da-ru',
  'de-en',
  'de-ru',
  'de-tr',
  'el-en',
  'el-ru',
  'en-cs',
  'en-da',
  'en-de',
  'en-el',
  'en-es',
  'en-et',
  'en-fi',
  'en-fr',
  'en-it',
  'en-lt',
  'en-lv',
  'en-nl',
  'en-no',
  'en-pt',
  'en-ru',
  'en-sk',
  'en-sv',
  'en-tr',
  'en-uk',
  'es-en',
  'es-ru',
  'et-en',
  'et-ru',
  'fi-en',
  'fi-ru',
  'fr-en',
  'fr-ru',
  'it-en',
  'it-ru',
  'lt-en',
  'lt-ru',
  'lv-en',
  'lv-ru',
  'nl-en',
  'nl-ru',
  'no-en',
  'no-ru',
  'pl-ru',
  'pt-en',
  'pt-ru',
  'ru-be',
  'ru-bg',
  'ru-cs',
  'ru-da',
  'ru-de',
  'ru-el',
  'ru-en',
  'ru-es',
  'ru-et',
  'ru-fi',
  'ru-fr',
  'ru-it',
  'ru-lt',
  'ru-lv',
  'ru-nl',
  'ru-no',
  'ru-pl',
  'ru-pt',
  'ru-sk',
  'ru-sv',
  'ru-tr',
  'ru-tt',
  'ru-uk',
  'sk-en',
  'sk-ru',
  'sv-en',
  'sv-ru',
  'tr-de',
  'tr-en',
  'tr-ru',
  'tt-ru',
  'uk-en',
  'uk-ru'
];
